// <auto-generated />
using MeetingService.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MeetingService.Data.Migrations
{
    [DbContext(typeof(MeetingDbContext))]
    [Migration("20260518120000_MeetingInviteResponses")]
    partial class MeetingInviteResponses
    {
    }
}
